schema_version = "1.0.0"
id = "ambientcg_material_importer_advanced"
version = "1.5.0"
name = "AmbientCG Material Importer Advanced"
tagline = "One-click material creation from AmbientCG with with advanced features"
maintainer = "Ruslan Norberg <elan@sestudio.org>"
type = "add-on"
website = "https://github.com/Elandig/blender-ambientcg-addon"
tags = ["Import-Export", "Material"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
network = "Makes calls to AmbientCG"
files = "Import and cache textures to disk"